### ISSUE TITLE
getOLAPFrame has never returned a result even though MDX works

### ISSUE THREAD

**Issue by MrRaymondLee** [jdeats76/OLAPRGateway#1]
I have different error messages when I run MDX.  The MDX I tested against the cube and returns values.  Right now I'm getting this error in R:

```
Failed to connect with OLAPRGateway. Error messageargument is of length zeroif (server_resp != "[]") {
    eval(parse(text = server_resp))
}
```

In the OLAPRGateway.exe console I get this error:

```
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at OLAPRGateway.Program.Main(String[] args)
>> flushing and restarting
>> Waiting for client connection on port 8888
```

Sometimes the query does work in the sense I see data coming in through console but in R I'll get this error:

```
Failed to connect with OLAPRGateway. Error message<text>:1:185: unexpected ','
1: Date_Day-Month-Quarter-Year_All <- c("0.0280517097695254");Date_Day-Month-Quarter-Year_All_Calendar2010 <- c("0.0290963998535984");Date_Day-Month-Quarter-Year_All_Calendar2010_Quarter1,
                                                                                                                                                                                            ^parse(text = server_resp)
```

I get the Parameter name: s error after trying various MDX.  It's strange that eventually it will "work" again in the sense I get the unexpected , error above.    

SQL Server 2012
R 3.3.1 64-bit
olaprgateway_1.0.tar
Windows 7 64-bit

**Comment by rventuradiaz** [comment]
Hi,
I've got the same error message. I use other port (2383) and trying to access a remote host in same network.
Would you please advise
Thanks
